### ISSUE TITLE
GIT_HEAD_SEMVER_IS_STABLE is truthy when it should not be

### ISSUE THREAD

**Issue by ezzatron** [make-files/adr#30]
The makefile generated by `lib-core/bin/generate-git-include` currently outputs all variables with quotes surrounding their values. This causes the value of `$GIT_HEAD_SEMVER_IS_STABLE` to be `""` when it actually needs to be an empty string for `make` to consider it falsy.

I *think* none of these variables should actually be quoted, since they are make variables, and make doesn't support quoted strings.

**Comment by jmalloc** [comment]
Well... that makes sense.
