### ISSUE TITLE
Make clean fails because binaries are missing.

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#36]
```console
$ make clean
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory clean-generated
rm -f --  codec/internal/fixtures/protobuf.pb.go
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory clean-ignored
git -c core.excludesfile= clean -dX --force 
Removing .makefiles/
Removing artifacts/
go clean -testcache
/bin/sh: ci-system-name: command not found
```

**Comment by ezzatron** [comment]
Working for me. Maybe needs some repro instructions?

**Comment by jmalloc** [comment]
Him, seems to occur for me pretty much unconditionally, here from a fresh clone:

```console
$ grit clone dogmatiq/marshalkit
probing 2 source(s) for dogmatiq/marshalkit
cwx: trying git@github.cwx.io:dogmatiq/marshalkit.git
github: trying git@github.com:dogmatiq/marshalkit.git
github: found git@github.com:dogmatiq/marshalkit.git
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Compressing objects: 100% (8/8), done.
Total 219 (delta 3), reused 5 (delta 2), pack-reused 209
/Users/james/grit/github.com/dogmatiq/marshalkit

$ make
--- executing core library installation hooks
--- fetching make-files/pkg-go@v1 repository archive
--- added make-files/pkg-go@v1 repository archive to the cache
--- unpacking go@v1 package archive
--- fetching make-files/pkg-protobuf@v1 repository archive
--- added make-files/pkg-protobuf@v1 repository archive to the cache
--- unpacking protobuf@v1 package archive
go test ./...
ok  	github.com/dogmatiq/marshalkit	0.015s
ok  	github.com/dogmatiq/marshalkit/codec	0.010s
?   	github.com/dogmatiq/marshalkit/codec/internal/fixtures	[no test files]
ok  	github.com/dogmatiq/marshalkit/codec/json	0.010s
ok  	github.com/dogmatiq/marshalkit/codec/protobuf	0.010s
?   	github.com/dogmatiq/marshalkit/fixtures	[no test files]

$ make clean
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory clean-generated
rm -f --  codec/internal/fixtures/protobuf.pb.go
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory clean-ignored
git -c core.excludesfile= clean -dX --force 
Removing .makefiles/
go clean -testcache
/bin/sh: ci-system-name: command not found
```

**Comment by jmalloc** [comment]
I just tested on the `dogmatiq/iago` as it doesn't have any `GENERATED_FILES`, just in case, but same behaviour.  Perhaps it's something go-specific messing with it (that `go clean -testcache` happens *after* the removal of the makefiles) :confused:

**Comment by ezzatron** [comment]
Did you accidentally hit "Close and comment"?

**Comment by jmalloc** [comment]
Uhh... maybe :)

**Comment by jmalloc** [comment]
It seems likely that this is caused by some additional `clean::` definition that executes after the one in lib-core, and hence after the makefiles themselves have been removed.

**Comment by jmalloc** [comment]
@ezzatron I am trying to solve this but struggling to come up with a solution that isn't a hack.

The problem is that `ci-system-name` is used to set the `MF_CI` and `MF_NON_INTERACTIVE` make variables, which always happens at include-time, but the `clean` target removes the `.makefiles` directory before this happens to get evaluated.

The best solution I can think of at the moment is to change `clean::` to `clean:` and add a `_clean::` target that is built before the makefiles are deleted in `clean:`. This would let language specific files hook into the clean process by adding a `_clean::` target but still allows the user to run `make clean`.

**Comment by jmalloc** [comment]
Fixed as described above in:

- https://github.com/make-files/lib-core/commit/e6cb4cf5204c0b6dc9890ab21eb00d2a919bf8ed
- https://github.com/make-files/pkg-go/compare/b96aa97e7a10dab521009fa527336309d1ae61e6...108ebf06d31f9621db245f62ae95bfd72c3b4756
