### ISSUE TITLE
Verification of generated protobuf files fails frequently.

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#41]
Because the tooling now includes the versions of tools used to generate the files, these builds fail even if there are no actual code changes and all of the tests would pass.

I think I'm at the point where I'm willing to just remove the generated file verification altogether, but I know we'll end up missing some other out-of-date file.

See [this build](https://github.com/dogmatiq/infix/runs/682805432?check_suite_focus=true#step:5:114).

**Comment by jmalloc** [comment]
@ezzatron I've just disabled `CI_VERIFY_GENERATED_FILES` by default, as of this issue the main (or possibly only) remaining reason for us to use this feature with Go is more annoying that useful now.

It can still be enabled by setting `CI_VERIFY_GENERATED_FILES` explicitly, but I don't think it's the kind of thing that anyone will ever remember to turn on so I'm pondering just getting rid of it now.  Any thoughts?

/cc @danilvpetrov

**Comment by ezzatron** [comment]
I think I do rely on that in my API docs repo, maybe somewhere else too. Fairly useful for static site generators. But Maybe we can push it off into a package for that kind of thing?

**Comment by jmalloc** [comment]
I'm happy to leave it in there but be disabled by default, you'd just have to turn it on for those API docs.

Ideally I'd have a better solution for this protobuf stuff, but it's got to the point now where every minor version bump in any PB-related library breaks the build.

**Comment by ezzatron** [comment]
Is there any point to `GENERATED_FILES` if `CI_VERIFY_GENERATED_FILES` gets removed? I'm guessing it's still used for some targets.

**Comment by danilvpetrov** [comment]
I am using those for embedded binary asset generation in Golang binaries.

**Comment by jmalloc** [comment]
Yeah, we still need the files to be generated when we build - that's still true for protobuf too - we'd just stop verifying that they get regenerated identically in CI.
