### ISSUE TITLE
Add suggestion to use DOCKER_TAGS to error message when trying to docker-push the dev tag

### ISSUE THREAD

**Issue by ezzatron** [make-files/adr#44]
Since we used to use `DOCKER_TAG`, devs are confused when it no longer works. This message:

    The 'dev' tag can not be pushed to the registry!

Could easily include a suggestion about how to "fix" the issue.

**Comment by jmalloc** [comment]
Fixed in https://github.com/make-files/pkg-docker/commit/6c5ad80ef25b61da42cd07fb5de342c922f7ed89
