### ISSUE TITLE
Collapse packages and libraries into a single repo.

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#50]
We should be able to do this without a BC break, as the `v1` downloader is hosted on GitHub pages at `makefiles.dev`.

I think we should probably rename the organisation to match that domain too, while we're at it. You can't have a dot in GitHub usernames, but perhaps `makefiles-dev` or `makefilesdev`.

**Comment by jmalloc** [comment]
It might also be useful to use this `issues` repo as that single repo, so we can keep all the issues without having to migrate them.

**Comment by ezzatron** [comment]
Seems reasonable. Should be a lot easier to make sweeping changes across packages.

**Comment by jmalloc** [comment]
Yep, and I think easier to keep them feeling consistent too.

**Comment by ezzatron** [comment]
Work here: https://github.com/make-files/makefiles/tree/monorepo-integration

**Comment by ezzatron** [comment]
I think this might already be working in a backwards-compatible way. This is all you need to try it out:

```patch
 .makefiles/%:
-       @curl -sfL https://makefiles.dev/v1 | bash /dev/stdin "$@"
+       @curl -sfL https://makefiles.dev/v1-monorepo | bash /dev/stdin "$@"
```

**Comment by ezzatron** [comment]
In terms of behavioural differences, I basically just had to:

- Remove `fetch-archive` and all references to it
- Change where the installer grabs the initial archive from

That's it. Pretty win.

**Comment by jmalloc** [comment]
Tried this out on a cwx go project that uses protobuf, seems fine :+1:

**Comment by ezzatron** [comment]
Done!. All package and lib repos are archived, and the installer now installs from the new [monorepo](https://github.com/make-files/makefiles).

FYI @na4ma4. Should be 100% backwards compatible, but let us know if you spot weirdness.

**Comment by ezzatron** [comment]
Since the monorepo retains all the commit history, it should be safe to delete the individual repos after a brief safety window.

**Comment by jmalloc** [comment]
Ooooeeee 🥳
