### ISSUE TITLE
Protobuf fully qualified imports fail for the files in the same repository

### ISSUE THREAD

**Issue by danilvpetrov** [make-files/adr#51]
When trying to specify a fully qualified import to  `*.proto` file in the same repository, the protobuf compilation fails with errors similar to this:

```
"foo.bar.Type" is already defined in file "path/to/local/file.proto".
```

Protoc version is `3.14.0`

**Comment by danilvpetrov** [comment]
Downgrading to protoc version `3.13.0` did not solve the issue.

**Comment by danilvpetrov** [comment]
Ok figured it out, apparently `artifacts/protobuf/go.proto_paths` file should contain the following entry in order for the local imports to work as fully qualified paths:
```
--proto_path=github.com/foo/bar=.
```
where `github.com/foo/bar` is the name of the current repository where the protobuf makefile target is executed.

**Comment by danilvpetrov** [comment]
Looks like modifying the `artifacts/protobuf/go.proto_paths` target as shown below is supposed to sort it out.

```diff

artifacts/protobuf/go.proto_paths: go.mod
	go mod download all
	mkdir -p $(@D)
+	go list -m -f "--proto_path={{.Path}}=." > $@
+	go list -f "--proto_path={{if .Dir}}{{ .Path }}={{ .Dir }}{{end}}" -m all >> $@
```

What are your thoughts @jmalloc? 

Should we also go and take out the dot import that is assigned to `PROTO_INCLUDE_PATHS` var to stop users having relative import paths for `*.proto` files in the same repository?

**Comment by danilvpetrov** [comment]
Ok I spoke too soon, scrap that solution I gave: it creates `github.com/foo/bar/proto.pb.go` directory structure within the repository which is completely awful.

**Comment by jmalloc** [comment]
I was pretty sure that the existing `go list` included the current module in the `go.proto_paths` file already. That's actually why I mentioned to you that we might be able to remove the `PROTO_PATHS += .` line altogether.

**Comment by danilvpetrov** [comment]
It does include it as an absolute path, but that still does not help the `protoc` to map the current repository correctly.

**Comment by jmalloc** [comment]
Hrm, I thought we were already using that in some commercial projects. I will link on slack.
