### ISSUE TITLE
ci target fails in golang when there are no GENERATED_FILES

### ISSUE THREAD

**Issue by na4ma4** [make-files/adr#52]
https://github.com/make-files/pkg-go/blob/v1/Makefile#L184
```makefile
artifacts/coverage/cover.out: artifacts/coverage/cover.tmp
	grep --fixed-strings --invert-match $(foreach F,$(GENERATED_FILES),-e "$F") "$<" > "$@"
```

If there are no `GENERATED_FILES` then it runs:
```shell
grep --fixed-strings --invert-match "artifacts/coverage/cover.tmp" > "artifacts/coverage/cover.out"
```

which is grepping STDIN and never returns (travis kills the build after 10 minutes of inactivity.

**Comment by jmalloc** [comment]
Fixed in https://github.com/make-files/pkg-go/commit/9a1d5df46d761524c2807ba973691eb3f93311e8.
