### ISSUE TITLE
precommit: ensure current year is present in LICENSE[.md]

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#57]
I always forget to update copyright year ranges in licences, short of (or in additional to) automating this, adding a simple grep check to the `precommit` recipe would be quite handy.

**Comment by ezzatron** [comment]
I did notice a really minor difference between our styles of `LICENSE` the other day. Yours seem to use `(c)` as a copyright symbol, whereas I use the Unicode symbol `©`. Might be relevant when implementing this.

**Comment by jmalloc** [comment]
I _think_ it would be adequate to literally grep for the current year with word boundaries and complain if it's not there.

**Comment by jmalloc** [comment]
I manage this through Terraform now, anyone else feel free to reopen if it's still relevant to your needs.
