### ISSUE TITLE
Multi-platform Docker builds

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#58]
This is an issue about adding support for building and publishing multi-platform manifests using the Docker makefile package. For an example of what I'm talking about, take a look at the [`postgres:latest`](https://hub.docker.com/_/postgres?tab=tags&name=latest&page=1&ordering=last_updated) tag, note that it lists multiple options under the `OS/ARCH` heading.

When requesting an image from the registry the Docker daemon chooses the appropriate target platform and downloads only those layers (as far as I can tell).

I became aware of this issue after a user of `jmalloc/echo-server` raised an issue pointing out that the architecture of the image has changed in the latest release, and hence does not work for them. This happened because I pushed the latest release from my M1 Mac. Previously, on all the machines we used regularly we were building `linux/arm64` by default, even on Macs.

## Stopgap solution

For most projects we build+push images under GitHub Actions, so they're always building on a Linux machine anyway, but even so I think we could and probably should hardcode the `--platform linux/amd64` argument to `docker build` in `v1` of the Docker makefiles.

Caveat to the above: Despite being able to run `linux/amd64` containers under Docker for Mac on an M1, in order to do so you need to specifically "ask" for the `linux/amd64` image, even if that's the only architecture published under a given tag.  This is possible when running a container with `docker run --platform`, but is not currently possible to do for a docker service, neither via `docker service create|update`, nor via a Docker stack/compose file.

## A real solution

With all of that in mind, IMO we should introduce proper support for multi-platform builds to the makefiles, most likely in a `v2` version of the Docker package.

I definitely haven't got a clear plan for how to achieve this, but here are some thoughts and challenges that I've identified so far:

### Build matrix

We'll likely want a `DOCKER_MATRIX` variable, similar to `GO_MATRIX`, which is how we list the target platforms ([example](https://github.com/jmalloc/grit/blob/master/Makefile#L1)).

### Platform-specific image content

For some projects we will need to provide platform-specific content at the project level. For example, for Go projects we will want to use binaries that target the same platform as the Docker image.

Other projects may not need to do this at the project level, for example, a Javascript project based on a Node.js image, where the upstream Node.js image already supports multiple platforms would add the same Javascript source/assets/whatever for every platform.

### Build limitations

1. You can't do multi-platform builds using `docker build`, you have to use `docker buildx` which does require some very minor configuration, or initialisation at least. Although this is still considered experimental (I think), is enabled by default on Docker for Mac, at least.

2. You can't do multi-platform builds in separate build & push steps like we do now. I believe this is because the Docker engine itself has no way to store the manifest that is produced by such a build. It has to be pushed to a registry as part of the build process in order to be of any use. FWIW You _can_ still do a multi-platform build without pushing, you just can't use the result of it. This may still be useful under CI to verify that the image can be built successfully.

---

I'll update this section as I think of things or we discuss them.

---

/cc @ezzatron, @na4ma4 , @danilvpetrov

**Comment by jmalloc** [comment]
`buildx` uses buildkit, which might also make https://github.com/make-files/makefiles/issues/55 irrelevant.

**Comment by ezzatron** [comment]
I have a possible edge-case here. A project where the image size is extreme (gigabytes of data served by a simple nginx container). If possible, I would want to avoid the situation where I was forced to push multiple copies of that data.

Either Docker can re-use the layer for all platform images, in which case it's already a solved problem, or I'd want to be able to limit the platforms being built to a specific one.

**Comment by jmalloc** [comment]
Does anyone see any reason _not_ to hardcode (or at least default to) passing `--platform linux/amd64` in the existing Docker makefiles?

**Comment by danilvpetrov** [comment]
> Does anyone see any reason not to hardcode (or at least default to) passing --platform linux/amd64 in the existing Docker makefiles?

I don't think I have any reasons not to.

**Comment by ezzatron** [comment]
> Does anyone see any reason _not_ to hardcode (or at least default to) passing `--platform linux/amd64` in the existing Docker makefiles?

No immediate objections.

**Comment by jmalloc** [comment]
Ok, going to add that at least.

Edit: Done in https://github.com/make-files/makefiles/pull/60.

**Comment by jmalloc** [comment]
FYI this is a blocker to provisioning dev swarms @ cwx. I'll try to come up with a plan for this, but would appreciate any input you might have.

**Comment by ezzatron** [comment]
> FYI this is a blocker to provisioning dev swarms @ cwx

In what way specifically is it a blocker? Just for people with ARM-based machines?

**Comment by jmalloc** [comment]
Yeah sorry, only for me, but I would like to have this solved before anyone else at work gets an ARM Mac.

**Comment by ezzatron** [comment]
Is there any way at all to run a non-ARM image? Like running it with Rosetta? Just preparing myself for the pain.

**Comment by jmalloc** [comment]
> Is there any way at all to run a non-ARM image? Like running it with Rosetta? Just preparing myself for the pain.

I think we happened to discuss this in person yesterday, but for posterity's sake:

> ... Despite being able to run `linux/amd64` containers under Docker for Mac on an M1, in order to do so you need to specifically "ask" for the `linux/amd64` image, even if that's the only architecture published under a given tag.  This is possible when running a container with `docker run --platform`, but is not currently possible to do for a docker service, neither via `docker service create|update`, nor via a Docker stack/compose file.

**Comment by jmalloc** [comment]
I was wrong about Docker (ie, _not_ the registry) not having a model for manifests, there is actually a `docker manifest` command now, although it is experimental still.

Edit: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by jmalloc** [comment]
This image https://github.com/orgs/make-files/packages/container/package/multi-arch-test is a test of multi-architecture builds intended to help us work out how, if at all, common layers are shared between multi-platform builds. It's built from the following Dockerfile:

```Dockerfile
# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM golang:alpine AS build
ARG BUILDPLATFORM
ARG TARGETPLATFORM
RUN echo "THIS LAYER IS THE SAME FOR ALL PLATFORMS" > /log.txt
RUN echo "THIS LAYER IS SPECIFIC TO $TARGETPLATFORM" >> /log.txt
FROM --platform=$TARGETPLATFORM golang:alpine 
RUN ls
```

Note that the earlier layers are common to all target platforms, it's only the last 3 commands that produce target-platform-specific layers.  Right now I have no idea how to analyse the manifest list to work out if these earlier layers are actually shared.

**Comment by jmalloc** [comment]
Ok, that was easy, but not looking good in terms of shared layers:

```
docker manifest inspect --verbose ghcr.io/make-files/multi-arch-test:latest
```

```json
[
	{
		"Ref": "ghcr.io/make-files/multi-arch-test:latest@sha256:debf6539cd32a87bb578d8e74cfffaf8e0cdcc5057d26988ff9ac3ded4a77bd2",
		"Descriptor": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"digest": "sha256:debf6539cd32a87bb578d8e74cfffaf8e0cdcc5057d26988ff9ac3ded4a77bd2",
			"size": 1365,
			"platform": {
				"architecture": "amd64",
				"os": "linux"
			}
		},
		"SchemaV2Manifest": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"schemaVersion": 2,
			"config": {
				"mediaType": "application/vnd.docker.container.image.v1+json",
				"digest": "sha256:cfb08664e9226e62facd876003e1475906e0e8991dcd95d80fb1c5aa1efe4199",
				"size": 4307
			},
			"layers": [
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:a0d0a0d46f8b52473982a3c466318f479767577551a53ffc9074c9fa7035982e",
					"size": 2814446
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:31adcdaf11c89113a810db23d523e549d634d7de695a72b0ce98a1f912101262",
					"size": 281508
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:b8b176561691ea11cfe541f3ee363a3aa67e3649eb3273bea62ebeea713eaecd",
					"size": 154
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:5ea3a45ba3ceb89332d4b57b631ffb8438f4ee6f7771a9ce7a3c3398e0aca882",
					"size": 110090606
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:19d3675075e91fc52d8438b6d9795a0b4475cc92b4f3dd704fe2a5c5bdb0cff8",
					"size": 155
				}
			]
		}
	},
	{
		"Ref": "ghcr.io/make-files/multi-arch-test:latest@sha256:fe84e9b1e6217184ed4c2b148e12f0751d745ccb642ec0ee7239c2ae7896d57b",
		"Descriptor": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"digest": "sha256:fe84e9b1e6217184ed4c2b148e12f0751d745ccb642ec0ee7239c2ae7896d57b",
			"size": 1365,
			"platform": {
				"architecture": "arm64",
				"os": "linux"
			}
		},
		"SchemaV2Manifest": {
			"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
			"schemaVersion": 2,
			"config": {
				"mediaType": "application/vnd.docker.container.image.v1+json",
				"digest": "sha256:225ce8d350b14a0b389873eac2bce437ba6148717cd613eed8283f332a4e8dcf",
				"size": 4305
			},
			"layers": [
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:552d1f2373af9bfe12033568ebbfb0ccbb0de11279f9a415a29207e264d7f4d9",
					"size": 2711827
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:ea3f2d53f512ea6320316a88e3c306ab2b3a98fccaeb99b4d3ae53c8bdea9e38",
					"size": 281685
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:9e70ebbbe112c904d5fa82be2f7801285d376cdf6feea060292096f84b51c668",
					"size": 154
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:420f46bb60c30a3aa3cb8d5f1df884c32c8c6e05ed3bf76b8488e7d3c42fdb97",
					"size": 104323711
				},
				{
					"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
					"digest": "sha256:ec8600cc17760f6a5cda1a3c9e3be31be1780f847b4411a0d6bf6d829aadedfd",
					"size": 156
				}
			]
		}
	}
]
```
