### ISSUE TITLE
Go get is deprecated for installing binaries, use go install

### ISSUE THREAD

**Issue by na4ma4** [make-files/adr#61]
As per the deprecation notice when using go 1.17

```plain
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

It seems this is how it works since at least go 1.16, do we need to support go 1.15 ? (should I check to see if it works as intended before 1.16 ?)

**Comment by jmalloc** [comment]
I am definitely reluctant to make a change like this without bumping the makefile version, but also don't think it's a pressing enough issue yet to warrant a new version.

It's probably best to support older Go versions if we can do so easily (thinking just a version switch). They (older versions) aren't used at cwx, but undoubtedly will be somewhere in our OSS projects. We also have no stats on how many other users we might have, though I'd be surprised if there's any outside our group.

**Comment by na4ma4** [comment]
It wouldn't be terrible to create a wrapper script that detected versions and worked around them, I mean although `1.15` isn't officially supported anymore, it's not that old for projects to be deprecated.

But also, it's only a problem during building and we'd expect anyone building _from now_ to be using a supported version.

**Comment by jmalloc** [comment]
Yeah, I changed my tune about this on your PR -- with Go's compatibility promise there's no compelling reason to support versions that aren't officially supported anymore. IM(new)O.
