### ISSUE TITLE
Mechanism for testing makefile changes before merging to `v1` branch.

### ISSUE THREAD

**Issue by jmalloc** [make-files/adr#64]
It would be handy if the download script had some option we could specify to ask for a branch other than `v1` of `make-files/makefiles`, just so we can test makefiles changes before we merge them. Perhaps just an environment variable or something like that.

This would be intended for internal use by us only, not for use by users.

**Comment by ezzatron** [comment]
Should be doable. Hardest part will be handling the directory name inside the archive. It's not always exactly the repo + branch name. For instance the `v1` branch is slugified as `makefiles-1` for some reason.
