### ISSUE TITLE
Provide a way to explicitly set the Telepresence **remote** service port

### ISSUE THREAD

**Issue by ezzatron** [make-files/adr#96]
In some of our services, we've starting having multiple ports, and Telepresence does not always try to intercept the expected port. It would be nice to be able to specify the remote port (or port name) via a Makefile/environment variable (perhaps `TELEPRESENCE_SERVICE_REMOTE_PORT`).

Usage would look like this:

    make intercept                                                # intercepts default remote port
    TELEPRESENCE_SERVICE_REMOTE_PORT=observability make intercept # intercepts custom named remote port

Where the Makefile might have a default port defined:

```Makefile
TELEPRESENCE_SERVICE_REMOTE_PORT := api
```

**Comment by jmalloc** [comment]
I nearly added this the other day, but what would be even better is being able to intercept _multiple_ ports as a single logical operation. It's not currently supported by Telepresence natively, but we could do it in the Makefiles.

**Comment by ezzatron** [comment]
Yeah, I suppose for `make intercept` that could work. Less so for `make intercept-run`.
